[build]
  base = "client/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  # Note: Add REACT_APP_API_URL in Netlify Dashboard → Site Settings → Environment Variables

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"